#cloud-config
packages:
- open-vm-tools
- epel-release
- strace
- tcpdump
- bind-utils
- tmux
- git
- python3-virtualenv
network:
 version: 2
 ethernets:
  eth0:
   match: {name: "eth0"}
   addresses:
   - ==IP==
   gateway4: ==GATEWAY==
   nameservers:
    search: [==DOMAIN==]
    addresses: [8.8.8.8,8.8.4.4]
runcmd:
- systemctl disable --now dnf-makecache.service dnf-makecache.timer
- dnf -y remove cockpit-ws
- dnf -y install systemd-networkd network-scripts
- dnf -y install https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/29/Everything/x86_64/os/Packages/p/pdsh-2.31-12.fc29.x86_64.rpm https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/29/Everything/x86_64/os/Packages/p/pdsh-rcmd-ssh-2.31-12.fc29.x86_64.rpm
- [sed, -i, 's/disable_root: 1/disable_root: 0/', /etc/cloud/cloud.cfg]
- systemctl disable NetworkManager
- systemctl stop NetworkManager
- systemctl mask NetworkManager
- echo -e 'DEVICE=eth0\nBOOTPROTO=none\nONBOOT=yes\nNM_CONTROLLED=no\n' > /etc/sysconfig/network-scripts/ifcfg-eth0
- echo -e '[Match]\nName=eth0\n[Network]\nDHCP=yes\nAddress===IP==\nGateway===GATEWAY==\nDNS=8.8.8.8\nLLMNR=no\nMulticastDNS=no\n[DHCPv4]\nClientIdentifier=mac\n' > /etc/systemd/network/80-eth0.network
- echo -e '[Match]\nName=vhost0\n[Network]\nDHCP=yes\nAddress===IP==\nGateway===GATEWAY==\nDNS=8.8.8.8\nLLMNR=no\nMulticastDNS=no\n[DHCPv4]\nClientIdentifier=mac\n' > /etc/systemd/network/80-vhost0.network
- [sed, -i, 's/disable_root: 1/disable_root: 0/', /etc/cloud/cloud.cfg]
- ln -fs /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
- [sed, -i, '0,/^hosts:/s/^\(hosts:.*\)/#&\nhosts:      resolve/', /etc/nsswitch.conf]
- [sed, -i, -e, 's/^#\(LLMNR\)=yes/\1=no/', -e, 's/^#\(MulticastDNS\)=yes/\1=no/', /etc/systemd/resolved.conf]
- systemctl enable networkd
- systemctl enable systemd-networkd
- systemctl enable systemd-resolved
- systemctl start systemd-networkd
- systemctl start systemd-resolved
- echo 'setw -g mouse' > /etc/tmux.conf
- [sed, -i, 's/SELINUX=enforcing/SELINUX=disabled/', /etc/selinux/config]
power_state:
 delay: "now"
 mode: reboot
 message: Rebooting with updated kernel
